services:
  - type: web
    name: naturinex-api
    runtime: node
    region: oregon
    plan: free
    buildCommand: rm -rf src/server && cd server && npm install
    startCommand: bash start-server.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://naturinex.com,https://www.naturinex.com,exp://