// 🏷️ Share Watermark Helper
// Automatically appends disclaimers and branding based on user tier

/**
 * Generate watermarked content for sharing
 * @param {string} suggestions - AI suggestions text
 * @param {string} medicationName - Name of medication scanned
 * @param {string} userTier - User's subscription tier
 * @param {object} user - User object (for premium branding)
 * @returns {string} - Watermarked content ready for sharing
 */
export const generateShareContent = (suggestions, medicationName, userTier, user = null) => {
  const timestamp = new Date().toLocaleDateString();
  const baseContent = `MEDICATION ANALYSIS: ${medicationName}\nGenerated: ${timestamp}\n\n${suggestions}`;
  
  switch (userTier) {
    case 'free':
      return `${baseContent}\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n🏷️ GENERATED BY Naturinex FREE\n\n⚠️ IMPORTANT DISCLAIMER:\n• This is AI-generated educational content\n• NOT professional medical advice\n• Always consult healthcare providers\n• For emergencies, contact medical services\n\n💎 Upgrade to Premium for:\n✓ Advanced AI analysis\n✓ Permanent storage\n✓ Ad-free sharing\n✓ Priority support\n\n🌐 Get Naturinex: https://Naturinex.app`;
      
    case 'basic':
      return `${baseContent}\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n📱 GENERATED BY Naturinex BASIC\n\n⚠️ MEDICAL DISCLAIMER:\n• AI-generated educational information only\n• Not a substitute for professional medical advice\n• Consult healthcare providers before making changes\n• Emergency situations require immediate medical attention\n\n🌐 Powered by Naturinex - Your AI Health Assistant`;
      
    case 'premium':
      return `${baseContent}\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n💎 Naturinex PREMIUM ANALYSIS\n${user?.displayName ? `Generated for: ${user.displayName}\n` : ''}⚠️ MEDICAL DISCLAIMER:\n• Advanced AI analysis for educational purposes\n• Professional medical consultation recommended\n• Not intended to replace healthcare provider advice\n• Contact emergency services for urgent health matters\n\n🌐 Naturinex Premium - Advanced AI Health Analysis`;
      
    case 'professional':
      return `${baseContent}\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n🏆 Naturinex PROFESSIONAL REPORT\n${user?.displayName ? `Healthcare Provider: ${user.displayName}\n` : ''}Analysis Date: ${timestamp}\nReport ID: MS-${Date.now()}\n\n⚠️ PROFESSIONAL DISCLAIMER:\n• AI-assisted analysis for healthcare professionals\n• Clinical judgment and patient evaluation required\n• Not a replacement for medical examination\n• For educational and reference purposes only\n\n📧 Questions? Contact: support@Naturinex.app\n🌐 Naturinex Professional - Healthcare AI Tools`;
      
    default:
      return baseContent;
  }
};

/**
 * Generate downloadable report with enhanced formatting
 * @param {string} suggestions - AI suggestions
 * @param {string} medicationName - Medication name
 * @param {string} userTier - User tier
 * @param {object} user - User object
 * @returns {object} - Download data with filename and content
 */
export const generateDownloadReport = (suggestions, medicationName, userTier, user = null) => {
  const timestamp = new Date().toISOString().slice(0, 19).replace(/[:.]/g, '-');
  const sanitizedMedName = medicationName.replace(/[^a-zA-Z0-9]/g, '_');
  
  const content = generateShareContent(suggestions, medicationName, userTier, user);
  
  const filename = `Naturinex_${sanitizedMedName}_${timestamp}.txt`;
  
  return {
    filename,
    content,
    mimeType: 'text/plain'
  };
};

/**
 * Generate email content with proper formatting
 * @param {string} suggestions - AI suggestions
 * @param {string} medicationName - Medication name  
 * @param {string} userTier - User tier
 * @param {object} user - User object
 * @returns {object} - Email data with subject and body
 */
export const generateEmailContent = (suggestions, medicationName, userTier, user = null) => {
  const tierName = {
    free: 'Free',
    basic: 'Basic', 
    premium: 'Premium',
    professional: 'Professional'
  }[userTier] || 'Basic';
  
  const subject = `Naturinex ${tierName} Analysis: ${medicationName}`;
  const body = generateShareContent(suggestions, medicationName, userTier, user);
  
  return {
    subject: encodeURIComponent(subject),
    body: encodeURIComponent(body)
  };
};

/**
 * Generate branding watermark based on tier
 * @param {string} userTier - User subscription tier
 * @returns {string} - Watermark text
 */
export const getBrandingWatermark = (userTier) => {
  const watermarks = {
    free: '🏷️ Generated by Naturinex Free - Upgrade for more features!',
    basic: '📱 Powered by Naturinex Basic',
    premium: '💎 Naturinex Premium Analysis',
    professional: '🏆 Naturinex Professional Report'
  };
  
  return watermarks[userTier] || watermarks.basic;
};

/**
 * Check if user can share without watermark
 * @param {string} userTier - User tier
 * @returns {boolean} - True if no watermark needed
 */
export const canShareWithoutWatermark = (userTier) => {
  return ['basic', 'premium', 'professional'].includes(userTier);
};