import React from 'react';
import {
  Box,
  Container,
  Typography,
  Button,
  Grid,
  Card,
  useTheme,
  useMediaQuery,
} from '@mui/material';
import { useNavigate } from 'react-router-dom';
import {
  LocalHospital,
  Security,
  Speed,
  CheckCircle,
} from '@mui/icons-material';
function WebHome() {
  const navigate = useNavigate();
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));
  const features = [
    {
      icon: <LocalHospital fontSize="large" />,
      title: 'Medication Lookup',
      description: 'Search medication names and get basic information',
    },
    {
      icon: <Speed fontSize="large" />,
      title: 'Text Recognition',
      description: 'Extract text from images using OCR technology',
    },
    {
      icon: <Security fontSize="large" />,
      title: 'Search History',
      description: 'Save and review your previous medication searches',
    },
    {
      icon: <CheckCircle fontSize="large" />,
      title: 'AI-Powered',
      description: 'Information generated by Gemini AI (not medical advice)',
    },
  ];
  return (
    <Box>
      {/* Critical Medical Disclaimer Banner */}
      <Box
        sx={{
          bgcolor: '#FEF3C7',
          borderBottom: '3px solid #F59E0B',
          py: 2,
          px: 2,
        }}
      >
        <Container maxWidth="lg">
          <Typography
            variant="h6"
            color="error"
            gutterBottom
            align="center"
            fontWeight="bold"
          >
            ⚠️ IMPORTANT MEDICAL DISCLAIMER
          </Typography>
          <Typography variant="body2" align="center" sx={{ fontWeight: 600 }}>
            This app is for EDUCATIONAL PURPOSES ONLY and is NOT medical advice.
            DO NOT make medication changes without consulting your healthcare provider.
            FOR EMERGENCIES: CALL 911 IMMEDIATELY.
          </Typography>
        </Container>
      </Box>

      {/* Hero Section */}
      <Box
        sx={{
          background: 'linear-gradient(135deg, #10B981 0%, #34D399 100%)',
          color: 'white',
          py: { xs: 8, md: 12 },
          px: 2,
        }}
      >
        <Container maxWidth="lg">
          <Grid container spacing={4} alignItems="center" justifyContent="center">
            <Grid item xs={12} md={10} lg={8}>
              <Box sx={{ textAlign: 'center' }}>
                <Typography
                  variant={isMobile ? 'h3' : 'h2'}
                  fontWeight="bold"
                  gutterBottom
                >
                  Educational Medication Information Resource
                </Typography>
                <Typography variant="h6" sx={{ mb: 2, opacity: 0.95 }}>
                  Research medication information and natural alternatives for educational purposes.
                </Typography>
                <Typography variant="body1" sx={{ mb: 4, opacity: 0.9, fontWeight: 500 }}>
                  Not medical advice. Always consult your healthcare provider.
                </Typography>
                <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', justifyContent: 'center' }}>
                  <Button
                    variant="contained"
                    size="large"
                    onClick={() => navigate('/login')}
                    sx={{
                      bgcolor: 'white',
                      color: 'primary.main',
                      '&:hover': {
                        bgcolor: 'grey.100',
                      },
                    }}
                  >
                    Get Started Free
                  </Button>
                  <Button
                    variant="outlined"
                    size="large"
                    onClick={() => navigate('/login')}
                    sx={{
                      borderColor: 'white',
                      color: 'white',
                      '&:hover': {
                        borderColor: 'white',
                        bgcolor: 'rgba(255, 255, 255, 0.1)',
                      },
                    }}
                  >
                    Sign In
                  </Button>
                </Box>
              </Box>
            </Grid>
          </Grid>
        </Container>
      </Box>
      {/* Features Section */}
      <Container maxWidth="lg" sx={{ py: 8 }}>
        <Typography variant="h3" align="center" fontWeight="bold" gutterBottom>
          Why Choose Naturinex?
        </Typography>
        <Typography
          variant="h6"
          align="center"
          color="text.secondary"
          sx={{ mb: 6 }}
        >
          Simple medication information lookup tool
        </Typography>
        <Grid container spacing={4}>
          {features.map((feature, index) => (
            <Grid item xs={12} sm={6} md={3} key={index}>
              <Card
                sx={{
                  height: '100%',
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  textAlign: 'center',
                  p: 3,
                  transition: 'transform 0.3s',
                  '&:hover': {
                    transform: 'translateY(-8px)',
                    boxShadow: '0 12px 24px rgba(0,0,0,0.1)',
                  },
                }}
              >
                <Box sx={{ color: 'primary.main', mb: 2 }}>
                  {feature.icon}
                </Box>
                <Typography variant="h6" fontWeight="bold" gutterBottom>
                  {feature.title}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  {feature.description}
                </Typography>
              </Card>
            </Grid>
          ))}
        </Grid>
      </Container>
      {/* CTA Section */}
      <Box sx={{
        background: 'linear-gradient(135deg, #10B981 0%, #34D399 100%)',
        py: 8,
        color: 'white'
      }}>
        <Container maxWidth="lg">
          <Typography variant="h3" align="center" fontWeight="bold" gutterBottom>
            Want to Learn About Natural Alternatives?
          </Typography>
          <Typography variant="h5" align="center" sx={{ mb: 4, opacity: 0.95 }}>
            Explore educational information about medications and natural alternatives
          </Typography>
          <Box sx={{ display: 'flex', justifyContent: 'center', gap: 2, flexWrap: 'wrap' }}>
            <Button
              variant="contained"
              size="large"
              onClick={() => navigate('/login')}
              sx={{
                bgcolor: 'white',
                color: 'primary.main',
                px: 4,
                py: 1.5,
                fontSize: '1.1rem',
                '&:hover': {
                  bgcolor: 'grey.100',
                },
              }}
            >
              Get Started Free
            </Button>
            <Button
              variant="outlined"
              size="large"
              onClick={() => navigate('/login')}
              sx={{
                borderColor: 'white',
                color: 'white',
                px: 4,
                py: 1.5,
                fontSize: '1.1rem',
                '&:hover': {
                  borderColor: 'white',
                  bgcolor: 'rgba(255,255,255,0.1)',
                },
              }}
            >
              View Plans
            </Button>
          </Box>
          {/* How It Works */}
          <Box sx={{ mt: 6, bgcolor: 'rgba(255,255,255,0.1)', borderRadius: 2, p: 4 }}>
            <Typography variant="h4" align="center" gutterBottom fontWeight="bold">
              How It Works
            </Typography>
            <Grid container spacing={3} sx={{ mt: 2 }}>
              <Grid item xs={12} md={4}>
                <Box sx={{ textAlign: 'center' }}>
                  <Typography variant="h2" fontWeight="bold" sx={{ mb: 1 }}>1</Typography>
                  <Typography variant="h6" gutterBottom>Enter Medication</Typography>
                  <Typography variant="body2" sx={{ opacity: 0.9 }}>
                    Type in the medication name or upload a photo of your prescription bottle
                  </Typography>
                </Box>
              </Grid>
              <Grid item xs={12} md={4}>
                <Box sx={{ textAlign: 'center' }}>
                  <Typography variant="h2" fontWeight="bold" sx={{ mb: 1 }}>2</Typography>
                  <Typography variant="h6" gutterBottom>AI Analysis</Typography>
                  <Typography variant="body2" sx={{ opacity: 0.9 }}>
                    Our AI researches potential natural alternatives (for educational purposes only)
                  </Typography>
                </Box>
              </Grid>
              <Grid item xs={12} md={4}>
                <Box sx={{ textAlign: 'center' }}>
                  <Typography variant="h2" fontWeight="bold" sx={{ mb: 1 }}>3</Typography>
                  <Typography variant="h6" gutterBottom">Consult Your Doctor</Typography>
                  <Typography variant="body2" sx={{ opacity: 0.9 }}>
                    Discuss findings with your healthcare provider before making any changes
                  </Typography>
                </Box>
              </Grid>
            </Grid>
          </Box>
        </Container>
      </Box>
      {/* Medical Disclaimer */}
      <Box sx={{ bgcolor: 'warning.light', py: 3 }}>
        <Container maxWidth="lg">
          <Typography variant="h6" gutterBottom align="center">
            ⚠️ Medical Disclaimer
          </Typography>
          <Typography variant="body2" align="center" sx={{ opacity: 0.9 }}>
            This app provides general medication information only. It is not a substitute for professional medical advice, diagnosis, or treatment.
            Always consult your physician or qualified healthcare provider with any questions about medications or health conditions.
            Never disregard professional medical advice or delay seeking it because of information provided by this app.
          </Typography>
        </Container>
      </Box>
      {/* Footer */}
      <Box sx={{ bgcolor: 'grey.900', color: 'white', py: 4, px: 2 }}>
        <Container maxWidth="lg">
          <Grid container spacing={4}>
            <Grid item xs={12} md={4}>
              <Typography variant="h6" gutterBottom>
                Naturinex
              </Typography>
              <Typography variant="body2" sx={{ opacity: 0.8 }}>
                Medication information lookup tool
              </Typography>
            </Grid>
            <Grid item xs={12} md={4}>
              <Typography variant="h6" gutterBottom>
                Legal
              </Typography>
              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
                <Button
                  color="inherit"
                  size="small"
                  onClick={() => navigate('/privacy')}
                  sx={{ justifyContent: 'flex-start' }}
                >
                  Privacy Policy
                </Button>
                <Button
                  color="inherit"
                  size="small"
                  onClick={() => navigate('/terms')}
                  sx={{ justifyContent: 'flex-start' }}
                >
                  Terms of Service
                </Button>
              </Box>
            </Grid>
            <Grid item xs={12} md={4}>
              <Typography variant="h6" gutterBottom>
                Contact
              </Typography>
              <Typography variant="body2" sx={{ opacity: 0.8 }}>
                support@naturinex.com
              </Typography>
            </Grid>
          </Grid>
          <Typography
            variant="body2"
            align="center"
            sx={{ mt: 4, pt: 2, borderTop: '1px solid rgba(255,255,255,0.1)' }}
          >
            © 2025 Naturinex. All rights reserved.
          </Typography>
        </Container>
      </Box>
    </Box>
  );
}
export default WebHome;