#!/usr/bin/env node
/**
 * Generate Secure Secrets for Production
 *
 * This script generates cryptographically secure secrets for:
 * - JWT_SECRET (512-bit)
 * - SESSION_SECRET (512-bit)
 * - ENCRYPTION_KEY (256-bit)
 *
 * Usage:
 *   node scripts/generate-secrets.js
 *
 * IMPORTANT:
 * - Save the output securely (password manager, secure note)
 * - Never commit these values to git
 * - Use EAS secrets / environment variables
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

console.log('\n🔐 NATURINEX SECURE SECRET GENERATOR\n');
console.log('=' .repeat(60));
console.log('Generating cryptographically secure secrets...\n');

// Generate secrets
const jwtSecret = crypto.randomBytes(64).toString('hex');
const sessionSecret = crypto.randomBytes(64).toString('hex');
const encryptionKey = crypto.randomBytes(32).toString('hex');

// Display secrets
console.log('✅ GENERATED SECRETS (Copy these to secure location):\n');
console.log('JWT_SECRET (512-bit):');
console.log(jwtSecret);
console.log('');

console.log('SESSION_SECRET (512-bit):');
console.log(sessionSecret);
console.log('');

console.log('ENCRYPTION_KEY (256-bit):');
console.log(encryptionKey);
console.log('');

console.log('=' .repeat(60));
console.log('\n📋 NEXT STEPS:\n');

console.log('1. Save these secrets to a secure password manager\n');

console.log('2. Add to EAS Secrets (mobile app):');
console.log('   eas secret:create --scope project --name JWT_SECRET --value "' + jwtSecret + '"');
console.log('   eas secret:create --scope project --name SESSION_SECRET --value "' + sessionSecret + '"');
console.log('   eas secret:create --scope project --name ENCRYPTION_KEY --value "' + encryptionKey + '"\n');

console.log('3. Add to Supabase Edge Functions:');
console.log('   supabase secrets set JWT_SECRET="' + jwtSecret + '"');
console.log('   supabase secrets set SESSION_SECRET="' + sessionSecret + '"');
console.log('   supabase secrets set ENCRYPTION_KEY="' + encryptionKey + '"\n');

console.log('4. Add to Vercel/Render (if using):');
console.log('   - Visit your deployment dashboard');
console.log('   - Update environment variables');
console.log('   - Redeploy\n');

console.log('5. Add to .env.local (local development):');
console.log('   echo "JWT_SECRET=' + jwtSecret + '" > .env.local');
console.log('   echo "SESSION_SECRET=' + sessionSecret + '" >> .env.local');
console.log('   echo "ENCRYPTION_KEY=' + encryptionKey + '" >> .env.local\n');

// Create a template file
const templatePath = path.join(__dirname, '..', '.env.production.template');
const templateContent = `# Naturinex Production Environment Configuration
# NEVER commit actual values to git
# Use this template to know what variables are needed

# 🔐 SECURITY SECRETS (Generated by scripts/generate-secrets.js)
JWT_SECRET=YOUR_JWT_SECRET_HERE
SESSION_SECRET=YOUR_SESSION_SECRET_HERE
ENCRYPTION_KEY=YOUR_ENCRYPTION_KEY_HERE

# 🔑 AUTHENTICATION
EXPO_PUBLIC_FIREBASE_API_KEY=
EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=naturinex-app.firebaseapp.com
EXPO_PUBLIC_FIREBASE_PROJECT_ID=naturinex-app
EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=naturinex-app.appspot.com
EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=
EXPO_PUBLIC_FIREBASE_APP_ID=

# 💾 DATABASE
EXPO_PUBLIC_SUPABASE_URL=https://hxhbsxzkzarqwksbjpce.supabase.co
EXPO_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=

# 💳 PAYMENTS
EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_live_
STRIPE_SECRET_KEY=sk_live_
STRIPE_WEBHOOK_SECRET=whsec_

# 🤖 AI SERVICES
GEMINI_API_KEY=
EXPO_PUBLIC_GEMINI_API_KEY=
GOOGLE_VISION_API_KEY=
EXPO_PUBLIC_GOOGLE_VISION_API_KEY=

# 📊 MONITORING
SENTRY_DSN=

# 🌐 API CONFIGURATION
EXPO_PUBLIC_API_URL=https://your-api-url.com

# 🚀 ENVIRONMENT
NODE_ENV=production
EXPO_PUBLIC_ENV=production
`;

try {
  fs.writeFileSync(templatePath, templateContent, 'utf8');
  console.log('✅ Created .env.production.template file\n');
} catch (error) {
  console.error('⚠️  Could not create template file:', error.message, '\n');
}

console.log('⚠️  SECURITY REMINDERS:');
console.log('   - NEVER commit .env.production to git');
console.log('   - NEVER share secrets in chat, email, or Slack');
console.log('   - NEVER use the same secrets for dev and production');
console.log('   - Rotate secrets every 90 days');
console.log('   - Monitor logs for unauthorized access\n');

console.log('=' .repeat(60));
console.log('\n✅ Secret generation complete!\n');
